// <auto-generated />
using System;
using CentralEvents.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CentralEvents.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200611211322_InitDb")]
    partial class InitDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DBO")
                .HasAnnotation("ProductVersion", "5.0.0-preview.4.20220.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CentralEvents.DataAccess.Contracts.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnzahlTickets")
                        .HasColumnName("AnzahlTickets")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventName")
                        .HasColumnName("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hausnummer")
                        .HasColumnName("Hausnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .HasColumnName("Nachname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .HasColumnName("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plz")
                        .HasColumnName("Plz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strasse")
                        .HasColumnName("Strasse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnName("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .HasColumnName("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BookingDetailsTable");
                });

            modelBuilder.Entity("CentralEvents.DataAccess.Contracts.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Benutzername")
                        .HasColumnName("Benutzername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hausnummer")
                        .HasColumnName("Hausnummer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nachname")
                        .HasColumnName("Nachname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .HasColumnName("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passwort")
                        .HasColumnName("Passwort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Plz")
                        .HasColumnName("Plz")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strasse")
                        .HasColumnName("Strasse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnName("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Vorname")
                        .HasColumnName("Vorname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CustomerTable");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Benutzername = "ceUser",
                            Email = "Hans.Werner@freemail.de",
                            Hausnummer = "66a",
                            Nachname = "Werner",
                            Ort = "Bremen",
                            Passwort = "lUgM3gwaOyfgUGaOB300LtJKsbYamO+hZGrdQVZkIYk=",
                            Plz = "28759",
                            Strasse = "Bremerstraße",
                            Telefon = "0421-555 888 22",
                            Vorname = "Hans"
                        });
                });

            modelBuilder.Entity("CentralEvents.DataAccess.Contracts.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BeginnUhrzeit")
                        .HasColumnName("BeginnUhrzeit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beschreibung")
                        .HasColumnName("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Datum")
                        .HasColumnName("Datum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Eintritt")
                        .HasColumnName("Eintritt")
                        .HasColumnType("float");

                    b.Property<string>("EndeUhrzeit")
                        .HasColumnName("EndeUhrzeit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GesamtanzahlEintrittskarten")
                        .HasColumnName("GesamtanzahlEintrittskarten")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .HasColumnName("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Restbestand")
                        .HasColumnName("Restbestand")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CentralEventsTable");
                });
#pragma warning restore 612, 618
        }
    }
}
