// <auto-generated />
using System;
using CentralEvents.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CentralEvents.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("DBO")
                .HasAnnotation("ProductVersion", "5.0.0-preview.4.20220.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CentralEvents.DataAccess.Contracts.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnName("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BeginnUhrzeit")
                        .HasColumnName("BeginnUhrzeit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Beschreibung")
                        .HasColumnName("Beschreibung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Datum")
                        .HasColumnName("Datum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Eintritt")
                        .HasColumnName("Eintritt")
                        .HasColumnType("float");

                    b.Property<string>("EndeUhrzeit")
                        .HasColumnName("EndeUhrzeit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnName("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ort")
                        .HasColumnName("Ort")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CentralEventsTable");
                });
#pragma warning restore 612, 618
        }
    }
}
